#!/usr/bin/env python3
"""Index the CJK corpus into a structured manifest.

PR-15 [feat]: lists every PDF under `audit/cjk-pdfs/{synthetic,real}/`,
groups by language (ja / zh / ko), and emits a JSON summary with
file size, sha256, and the synthetic-fixture ground truth (if known).

This script is the corpus inventory layer for `v1_4_cjk_run.py`. It
deliberately does NOT run pdf.zig; the harness picks up its output.

Conventions:
  - `audit/cjk-pdfs/synthetic/manifest.json` is generated by
    `zig build gen-cjk-corpus` and carries the expected UTF-8 text +
    wmode for each synthetic fixture.
  - `audit/cjk-pdfs/real/*.pdf` filenames must start with the language
    tag (`ja-`, `zh-`, or `ko-`) so the indexer can group them. Real
    PDFs have no expected-text ground truth (the comparison runs
    against pymupdf4llm at extraction time, not against a static
    string).

Usage:
    python3 audit/cjk_subset.py [--out audit/cjk_corpus_index.json]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional

PROJECT = Path(__file__).resolve().parent.parent
SYNTHETIC_DIR = PROJECT / "audit" / "cjk-pdfs" / "synthetic"
REAL_DIR = PROJECT / "audit" / "cjk-pdfs" / "real"

LANGS = ("ja", "zh", "ko")


@dataclass
class CorpusEntry:
    id: str
    lang: str
    source: str  # "synthetic" | "real"
    path: str  # absolute
    size_bytes: int
    sha256: str
    wmode: Optional[int] = None
    expected_utf8: Optional[str] = None


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def load_synthetic_manifest() -> dict[str, dict]:
    """Read the manifest emitted by `zig build gen-cjk-corpus`."""
    manifest_path = SYNTHETIC_DIR / "manifest.json"
    if not manifest_path.exists():
        return {}
    with manifest_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return {entry["id"]: entry for entry in data.get("fixtures", [])}


def detect_lang_from_filename(name: str) -> Optional[str]:
    for lang in LANGS:
        if name.startswith(f"{lang}-") or name.startswith(f"{lang}_"):
            return lang
    return None


def collect_synthetic() -> list[CorpusEntry]:
    out: list[CorpusEntry] = []
    if not SYNTHETIC_DIR.exists():
        return out
    manifest = load_synthetic_manifest()
    for pdf in sorted(SYNTHETIC_DIR.glob("*.pdf")):
        fid = pdf.stem
        meta = manifest.get(fid, {})
        lang = meta.get("lang") or detect_lang_from_filename(fid)
        if lang is None:
            continue
        out.append(
            CorpusEntry(
                id=fid,
                lang=lang,
                source="synthetic",
                path=str(pdf),
                size_bytes=pdf.stat().st_size,
                sha256=sha256_file(pdf),
                wmode=meta.get("wmode"),
                expected_utf8=meta.get("expected_utf8"),
            )
        )
    return out


def collect_real() -> list[CorpusEntry]:
    out: list[CorpusEntry] = []
    if not REAL_DIR.exists():
        return out
    for pdf in sorted(REAL_DIR.glob("*.pdf")):
        lang = detect_lang_from_filename(pdf.stem)
        if lang is None:
            print(f"warning: skipping {pdf.name} — no ja-/zh-/ko- prefix", file=sys.stderr)
            continue
        out.append(
            CorpusEntry(
                id=pdf.stem,
                lang=lang,
                source="real",
                path=str(pdf),
                size_bytes=pdf.stat().st_size,
                sha256=sha256_file(pdf),
                wmode=None,
                expected_utf8=None,
            )
        )
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", default=str(PROJECT / "audit" / "cjk_corpus_index.json"))
    args = p.parse_args()

    synthetic = collect_synthetic()
    real = collect_real()
    all_entries = synthetic + real

    by_lang_synthetic = {lang: sum(1 for e in synthetic if e.lang == lang) for lang in LANGS}
    by_lang_real = {lang: sum(1 for e in real if e.lang == lang) for lang in LANGS}

    summary = {
        "version": 1,
        "totals": {
            "synthetic": len(synthetic),
            "real": len(real),
            "by_lang_synthetic": by_lang_synthetic,
            "by_lang_real": by_lang_real,
        },
        "entries": [asdict(e) for e in all_entries],
    }

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")

    print(
        f"indexed {len(synthetic)} synthetic + {len(real)} real PDFs "
        f"(ja={by_lang_synthetic['ja'] + by_lang_real['ja']}, "
        f"zh={by_lang_synthetic['zh'] + by_lang_real['zh']}, "
        f"ko={by_lang_synthetic['ko'] + by_lang_real['ko']})",
        file=sys.stderr,
    )
    print(f"wrote {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
